CI/CD Integration
particle-iot/device-os-test pull request #4
Opened 2021-11-26 18:18 UTC by sergeuz

2021-11-29 17:25 UTC, joegoggins requested changes
Thanks @sergeuz . I took this for a spin and discovered a couple of things. I fixed some (see my commits pushed to branch) and left a couple for you. See [notes](https://app.shortcut.com/particle/story/91839/setup-device-os-test-runner-to-run-linter-tests-in-circleci#activity-92870) for details, and sub-tasks for work remaining. Let me know if you have any questions.

2021-11-29 17:25 UTC, joegoggins commented on .github/workflows/ci.yaml
> +            optional: true
Let's comment these lines out so the build starts green on Node 12

2021-11-29 18:29 UTC, laupow commented
@monkbroc drafted a good pipeline for npm packages in Circle mongoose-models PR 273

Is there time this sprint to switch to Circle? Since CI is under maintenance this sprint anyways, this is a good opportunity  to build some mindshare around publishing npm modules in Circle

The only bit to add on top of Julien's PR may be matrix builds: https://circleci.com/blog/circleci-matrix-jobs/. Happy to help get the matrix bit working

2021-12-03 13:57 UTC, sergeuz commented
Thanks for letting me know, @laupow. I'll look into moving this repo to CircleCI but I'm not sure when I have time for that. The goal of this PR was not just to add a CI/CD config to this repo but also bring it up to our basic standards in regards to automatic testing, code style and etc. I picked GitHub Actions because I'm familiar with them, but now that the dirty work is done we can switch the CI/CD system used by this repo at any time.

2021-12-03 16:07 UTC, joegoggins approved these changes
Tests are now passing for me. Looks good. LTGM.

@laupow regarding the ask to move this to CircleCI, I enqueued this for later: https://app.shortcut.com/particle/story/93359/migrate-device-os-flash-util-and-device-os-test-runner-to-circleci

Sergey, I don't believe there is fierce urgency on that, so feel free to tackle whenever you have a chance. Given the great CircleCI npm lib reference model that Julien shared in https://github.com/particle-iot/mongoose-models/pull/273 , I don't think it will take more than an hour for both repos.

2021-12-03 16:13 UTC, merged